### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by eliias** [eliias/isorun#122]
# Roadmap

For now, `isorun` is an experiment, but to make this a usable foundation for Ruby on Rails app development, there should be some product goals. The vision is to enable “Frictionless development of modern web apps with React and Rails”.

- [ ] Setup new Ruby on Rails project w/ isorun (Generator, Automated Upgrades)
- [ ] Out-of-the-box server-side rendering for development and production
- [ ] Seamless state transfer between backend and frontend
- [ ] Support for server components
- [ ] Local-first software (CRDT's, Local state, …)
